package com.app.novastore.errors;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

import static com.app.novastore.errors.ConstantErrorMessage.*;


@Getter
@AllArgsConstructor
public enum AppErrorCodes {
    NOT_IMPLEMENTED_YET(NOT_IMPLEMENTED_YET_EN, NOT_IMPLEMENTED_YET_FA, HttpStatus.NOT_IMPLEMENTED),
    RECORD_NOT_FOUND(RECORD_NOT_FOUND_EN, RECORD_NOT_FOUND_FA, HttpStatus.NOT_FOUND),
    USER_DISABLED(USER_DISABLED_EN, USER_DISABLED_FA, HttpStatus.FORBIDDEN),
    INCORRECT_OTP_CODE(INCORRECT_OTP_CODE_EN, INCORRECT_OTP_CODE_FA, HttpStatus.BAD_REQUEST),
    OTP_REQUEST_COUNT_EXCEEDED(OTP_REQUEST_COUNT_EXCEEDED_EN, OTP_REQUEST_COUNT_EXCEEDED_FA, HttpStatus.TOO_MANY_REQUESTS),
    FORBIDDEN(FORBIDDEN_EN, FORBIDDEN_FA, HttpStatus.FORBIDDEN),
    UNAUTHORIZED(UNAUTHORIZED_EN, UNAUTHORIZED_FA, HttpStatus.UNAUTHORIZED),
    CONSTRAINT_VALIDATION(CONSTRAINT_VALIDATION_EN, CONSTRAINT_VALIDATION_FA, HttpStatus.BAD_REQUEST),
    MALFORMED_REQUEST(MALFORMED_REQUEST_EN, MALFORMED_REQUEST_FA, HttpStatus.BAD_REQUEST),
    DATABASE_CONSTRAINTS_VIOLATED(DATABASE_CONSTRAINTS_VIOLATED_EN, DATABASE_CONSTRAINTS_VIOLATED_FA, HttpStatus.UNPROCESSABLE_ENTITY),
    UPDATE_FAILED(UPDATE_FAILED_EN, UPDATE_FAILED_FA, HttpStatus.NOT_MODIFIED),
    ROUTE_NOT_SUPPORTED(ROUTE_NOT_SUPPORTED_EN, ROUTE_NOT_SUPPORTED_FA, HttpStatus.BAD_REQUEST),
    ROUTE_DISCONTINUITY_EXCEPTION(ROUTE_DISCONTINUITY_EXCEPTION_EN, ROUTE_DISCONTINUITY_EXCEPTION_FA, HttpStatus.BAD_REQUEST),
    INVALID_FLEET_COMPANY_ID(INVALID_FLEET_COMPANY_ID_EN, INVALID_FLEET_COMPANY_ID_FA, HttpStatus.NOT_ACCEPTABLE),
    CATEGORY_NOT_FOUND(CATEGORY_NOT_FOUND_EN, CATEGORY_NOT_FOUND_FA, HttpStatus.NOT_FOUND),
    DUPLICATE_RECORD(DUPLICATE_RECORD_EN, DUPLICATE_RECORD_FA, HttpStatus.CONFLICT),
    SERVICE_TEMPORARY_UNAVAILABLE(SERVICE_TEMPORARY_UNAVAILABLE_EN, SERVICE_TEMPORARY_UNAVAILABLE_FA, HttpStatus.SERVICE_UNAVAILABLE),
    ASSET_NOT_TRADABLE(ASSET_NOT_TRADABLE_EN, ASSET_NOT_TRADABLE_FA, HttpStatus.BAD_REQUEST),
    INVALID_ORDER_STATUS_TRANSITION(INVALID_ORDER_STATUS_TRANSITION_EN, INVALID_ORDER_STATUS_TRANSITION_FA, HttpStatus.CONFLICT),
    ORDER_RESERVATION_EXPIRED(ORDER_RESERVATION_EXPIRED_EN, ORDER_RESERVATION_EXPIRED_FA, HttpStatus.CONFLICT),
    MARKET_CLOSED(MARKET_CLOSED_EN, MARKET_CLOSED_FA, HttpStatus.CONFLICT),
    ORDER_QUANTITY_OUT_OF_RANGE(ORDER_QUANTITY_OUT_OF_RANGE_EN, ORDER_QUANTITY_OUT_OF_RANGE_FA, HttpStatus.BAD_REQUEST),
    ORDER_QUANTITY_STEP_MISMATCH(ORDER_QUANTITY_STEP_MISMATCH_EN, ORDER_QUANTITY_STEP_MISMATCH_FA, HttpStatus.BAD_REQUEST),
    TRADE_LIMIT_EXCEEDED(TRADE_LIMIT_EXCEEDED_EN, TRADE_LIMIT_EXCEEDED_FA, HttpStatus.FORBIDDEN),
    PRICE_NOT_AVAILABLE(PRICE_NOT_AVAILABLE_EN, PRICE_NOT_AVAILABLE_FA, HttpStatus.SERVICE_UNAVAILABLE),
    DEVIATION_THRESHOLD_NOT_FOUND(DEVIATION_THRESHOLD_NOT_FOUND_EN, DEVIATION_THRESHOLD_NOT_FOUND_FA, HttpStatus.INTERNAL_SERVER_ERROR),
    ORDER_NOT_FOUND(ORDER_NOT_FOUND_EN, ORDER_NOT_FOUND_FA, HttpStatus.NOT_FOUND),
    ORDER_ACCESS_DENIED(ORDER_ACCESS_DENIED_EN, ORDER_ACCESS_DENIED_FA, HttpStatus.FORBIDDEN),
    ORDER_CODE_GENERATION_FAILED(ORDER_CODE_GENERATION_FAILED_EN, ORDER_CODE_GENERATION_FAILED_FA, HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_PERMANENT_HAS_END_DATE(EVENT_PERMANENT_HAS_END_DATE_EN, EVENT_PERMANENT_HAS_END_DATE_FA, HttpStatus.BAD_REQUEST),
    EVENT_TEMPORARY_MISSING_END_DATE(EVENT_TEMPORARY_MISSING_END_DATE_EN, EVENT_TEMPORARY_MISSING_END_DATE_FA, HttpStatus.BAD_REQUEST),
    EVENT_END_DATE_BEFORE_START_DATE(EVENT_END_DATE_BEFORE_START_DATE_EN, EVENT_END_DATE_BEFORE_START_DATE_FA, HttpStatus.BAD_REQUEST),
    EVENT_INACTIVE_REASON_REQUIRED(EVENT_INACTIVE_REASON_REQUIRED_EN, EVENT_INACTIVE_REASON_REQUIRED_FA, HttpStatus.BAD_REQUEST),
    EVENT_ACTION_INCOMPLETE(EVENT_ACTION_INCOMPLETE_EN, EVENT_ACTION_INCOMPLETE_FA, HttpStatus.BAD_REQUEST),
    EVENT_PUBLISHED_DATE_REQUIRED(EVENT_PUBLISHED_DATE_REQUIRED_EN, EVENT_PUBLISHED_DATE_REQUIRED_FA, HttpStatus.BAD_REQUEST),
    ;
    private final String code;
    private final String englishMessage;
    private final String persianMessage;
    private final HttpStatus status;

    AppErrorCodes(String englishMessage, String persianMessage, HttpStatus status) {
        this.code = name();
        this.englishMessage = englishMessage;
        this.persianMessage = persianMessage;
        this.status = status;
    }
}
